### ISSUE TITLE
Report.user_created" must be a "User" instance.

### ISSUE THREAD

**Issue by lsh-0** [groveco/django-sql-explorer#200]
Hi guys,

After:

1. following the installation instructions
2. navigating to `/report_builder/` 
3. clicking big pink button
4. clicking 'add report'
5. entering 'asdf' as name and description and selecting my model table

I get:

* no error in the GUI
* an XHR request failing with a 500 response
* this stacktrace from the development server

```
Internal Server Error: /report_builder/api/report/
Traceback (most recent call last):
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/report_builder/api/views.py", line 50, in perform_create
    serializer.save(user_created=self.request.user)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 191, in save
    self.instance = self.create(validated_data)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 846, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/query.py", line 399, in create
    obj = self.model(**kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/base.py", line 431, in __init__
    setattr(self, field.name, rel_obj)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "<django.contrib.auth.models.AnonymousUser object at 0x7f212c013d90>": "Report.user_created" must be a "User" instance.
Internal Server Error: /report_builder/api/report/
Traceback (most recent call last):
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/report_builder/api/views.py", line 50, in perform_create
    serializer.save(user_created=self.request.user)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 191, in save
    self.instance = self.create(validated_data)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 846, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/query.py", line 399, in create
    obj = self.model(**kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/base.py", line 431, in __init__
    setattr(self, field.name, rel_obj)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "<django.contrib.auth.models.AnonymousUser object at 0x7f212c013d90>": "Report.user_created" must be a "User" instance.
[16/May/2016 14:10:36] "POST /report_builder/api/report/ HTTP/1.1" 500 142350
```

I have installed:

* Django==1.9
* django-rest-swagger==0.3.4
* djangorestframework==3.3.2
* django-report-builder==3.3.0
* django-report-utils==0.3.15

Thanks for your time.

**Comment by chrisclark** [comment]
Hey Luke -- I think you may have meant to file this issue against django
report builder, not SQL Explorer.

On May 16, 2016, at 7:17 AM, Luke Skibinski <notifications@github.com>
wrote:

Hi guys,

After:

   1. following the installation instructions
   2. navigating to /report_builder/
   3. clicking big pink button
   4. clicking 'add report'
   5. entering 'asdf' as name and description and selecting my model table

I get:

   - no error in the GUI
   - an XHR request failing with a 500 response
   - this stacktrace from the development server

Internal Server Error: /report_builder/api/report/
Traceback (most recent call last):
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py",
line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py",
line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py",
line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/viewsets.py",
line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py",
line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py",
line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/mixins.py",
line 21, in create
    self.perform_create(serializer)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/report_builder/api/views.py",
line 50, in perform_create
    serializer.save(user_created=self.request.user)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py",
line 191, in save
    self.instance = self.create(validated_data)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py",
line 846, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/manager.py",
line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/query.py",
line 399, in create
    obj = self.model(**kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/base.py",
line 431, in __init__
    setattr(self, field.name, rel_obj)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py",
line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "<django.contrib.auth.models.AnonymousUser
object at 0x7f212c013d90>": "Report.user_created" must be a "User"
instance.
Internal Server Error: /report_builder/api/report/
Traceback (most recent call last):
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py",
line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py",
line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py",
line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/viewsets.py",
line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py",
line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py",
line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/mixins.py",
line 21, in create
    self.perform_create(serializer)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/report_builder/api/views.py",
line 50, in perform_create
    serializer.save(user_created=self.request.user)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py",
line 191, in save
    self.instance = self.create(validated_data)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py",
line 846, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/manager.py",
line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/query.py",
line 399, in create
    obj = self.model(**kwargs)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/base.py",
line 431, in __init__
    setattr(self, field.name, rel_obj)
  File "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py",
line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "<django.contrib.auth.models.AnonymousUser
object at 0x7f212c013d90>": "Report.user_created" must be a "User"
instance.
[16/May/2016 14:10:36] "POST /report_builder/api/report/ HTTP/1.1" 500 142350

I have installed:

   - Django==1.9
   - django-rest-swagger==0.3.4
   - djangorestframework==3.3.2
   - django-report-builder==3.3.0
   - django-report-utils==0.3.15

Thanks for your time.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/groveco/django-sql-explorer/issues/200>

**Comment by lsh-0** [comment]
nuts, you're right. sorry about that, I have the two open side by side and
must have gotten confused.

On Mon, May 16, 2016 at 4:19 PM, Chris Clark <notifications@github.com>
wrote:

> Hey Luke -- I think you may have meant to file this issue against django
> report builder, not SQL Explorer.
>
> On May 16, 2016, at 7:17 AM, Luke Skibinski <notifications@github.com>
> wrote:
>
> Hi guys,
>
> After:
>
> 1. following the installation instructions
> 2. navigating to /report_builder/
> 3. clicking big pink button
> 4. clicking 'add report'
> 5. entering 'asdf' as name and description and selecting my model table
>
> I get:
>
> - no error in the GUI
> - an XHR request failing with a 500 response
> - this stacktrace from the development server
>
> Internal Server Error: /report_builder/api/report/
> Traceback (most recent call last):
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py",
> line 149, in get_response
> response = self.process_exception_by_middleware(e, request)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py",
> line 147, in get_response
> response = wrapped_callback(request, *callback_args, **callback_kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py",
> line 58, in wrapped_view
> return view_func(*args, **kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/viewsets.py",
> line 87, in view
> return self.dispatch(request, *args, **kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py",
> line 466, in dispatch
> response = self.handle_exception(exc)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py",
> line 463, in dispatch
> response = handler(request, *args, **kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/mixins.py",
> line 21, in create
> self.perform_create(serializer)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/report_builder/api/views.py",
> line 50, in perform_create
> serializer.save(user_created=self.request.user)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py",
> line 191, in save
> self.instance = self.create(validated_data)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py",
> line 846, in create
> instance = ModelClass.objects.create(**validated_data)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/manager.py",
> line 122, in manager_method
> return getattr(self.get_queryset(), name)(*args, **kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/query.py",
> line 399, in create
> obj = self.model(**kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/base.py",
> line 431, in __init__
> setattr(self, field.name, rel_obj)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py",
> line 207, in __set__
> self.field.remote_field.model._meta.object_name,
> ValueError: Cannot assign "<django.contrib.auth.models.AnonymousUser
> object at 0x7f212c013d90>": "Report.user_created" must be a "User"
> instance.
> Internal Server Error: /report_builder/api/report/
> Traceback (most recent call last):
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py",
> line 149, in get_response
> response = self.process_exception_by_middleware(e, request)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/core/handlers/base.py",
> line 147, in get_response
> response = wrapped_callback(request, *callback_args, **callback_kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py",
> line 58, in wrapped_view
> return view_func(*args, **kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/viewsets.py",
> line 87, in view
> return self.dispatch(request, *args, **kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py",
> line 466, in dispatch
> response = self.handle_exception(exc)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/views.py",
> line 463, in dispatch
> response = handler(request, *args, **kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/mixins.py",
> line 21, in create
> self.perform_create(serializer)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/report_builder/api/views.py",
> line 50, in perform_create
> serializer.save(user_created=self.request.user)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py",
> line 191, in save
> self.instance = self.create(validated_data)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/rest_framework/serializers.py",
> line 846, in create
> instance = ModelClass.objects.create(**validated_data)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/manager.py",
> line 122, in manager_method
> return getattr(self.get_queryset(), name)(*args, **kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/query.py",
> line 399, in create
> obj = self.model(**kwargs)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/base.py",
> line 431, in __init__
> setattr(self, field.name, rel_obj)
> File
> "/home/luke/dev/python/lax/develop/venv/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py",
> line 207, in __set__
> self.field.remote_field.model._meta.object_name,
> ValueError: Cannot assign "<django.contrib.auth.models.AnonymousUser
> object at 0x7f212c013d90>": "Report.user_created" must be a "User"
> instance.
> [16/May/2016 14:10:36] "POST /report_builder/api/report/ HTTP/1.1" 500
> 142350
>
> I have installed:
>
> - Django==1.9
> - django-rest-swagger==0.3.4
> - djangorestframework==3.3.2
> - django-report-builder==3.3.0
> - django-report-utils==0.3.15
>
> Thanks for your time.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/groveco/django-sql-explorer/issues/200>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/groveco/django-sql-explorer/issues/200#issuecomment-219453241>
>



-- 

Luke Skibinski

Formally defined,
Extensively tested,
Cryptic, abstract, thing.

--

eLife Sciences Publications, Ltd is a limited liability non-profit
non-stock corporation incorporated in the State of Delaware, USA, with
company number 5030732, and is registered in the UK with company number
FC030576 and branch number BR015634 at the address First Floor, 24 Hills
Road, Cambridge CB2 1JP.
