### ISSUE TITLE
older version install?

### ISSUE THREAD

**Issue by kostiag** [groveco/django-sql-explorer#231]
I am on Django 1.6 and I am trying to install Version 0.6 getting Exception below can anyone help? Unfortunately not able to upgrade Django at this time. 
pip install django-sql-explorer=0.6
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pip/req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pip/req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2606, in parse
    reqs = list(parse_requirements(s))
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2544, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2512, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'django-sql-explorer=0.6', 'at', '=0.6')

**Comment by kostiag** [comment]
==0.6 :-)
