### ISSUE TITLE
Error when running makemigrations

### ISSUE THREAD

**Issue by bigblind** [groveco/django-sql-explorer#262]
When I run `manage.py makemigrations`, I get the following error:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/frederikcreemers/.virtualenvs/employebla/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/frederikcreemers/.virtualenvs/employebla/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/frederikcreemers/.virtualenvs/employebla/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/frederikcreemers/.virtualenvs/employebla/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/frederikcreemers/.virtualenvs/employebla/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 65, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/Users/frederikcreemers/.virtualenvs/employebla/lib/python2.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/frederikcreemers/.virtualenvs/employebla/lib/python2.7/site-packages/django/db/migrations/loader.py", line 306, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/Users/frederikcreemers/.virtualenvs/employebla/lib/python2.7/site-packages/django/db/migrations/loader.py", line 276, in _reraise_missing_dependency
    raise exc
django.db.migrations.exceptions.NodeNotFoundError: Migration common.0001_initial dependencies reference nonexistent parent node (u'auth', u'0008_alter_user_username_max_length')
```

I've swapped out Django's `auth.User` model for my own, not sure if that could be causing the problem.

**Comment by bigblind** [comment]
Sorry, looking at this more closely, this looks like an error that's not specific to this project.
