### ISSUE TITLE
cannot connect to models

### ISSUE THREAD

**Issue by johnnybhojwani** [groveco/django-sql-explorer#391]
followed all instructions, had to make a few updates (render_to_respond is deprecated). Got the UI to show up but it does not connect to any tables (models). Error says no such table. Tried the schema and it shows an error as shown below:

Traceback (most recent call last):
  File "C:\Users\johnny_bhojwani\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 89, in join
    for p in map(os.fspath, paths):

During handling of the above exception (expected str, bytes or os.PathLike object, not dict), another exception occurred:
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\views\decorators\clickjacking.py", line 33, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\explorer\views.py", line 169, in dispatch
    return super(SchemaView, self).dispatch(*args, **kwargs)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\explorer\views.py", line 93, in dispatch
    return super(PermissionRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\explorer\views.py", line 178, in get
    {'schema': schema_info(connection)})
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\template\loaders\base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\template\loaders\filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "C:\Users\johnny_bhojwani\Box Sync\GreenThumb\GreenThumbProject\.venv\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\johnny_bhojwani\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 115, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\johnny_bhojwani\AppData\Local\Programs\Python\Python37\lib\genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None

Exception Type: TypeError at /explorer/schema/default
Exception Value: join() argument must be str or bytes, not 'dict'

**Comment by marksweb** [comment]
What are your settings?

There's a new version soon to release which would be worth trying out. It officially brings support for django 3 & drops the use of `render_to_response`
