### ISSUE TITLE
Failing smoke tests: AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by jayvdb** [groveco/django-sql-explorer#394]
Using `django-smoke-tests`, sql-explorer is breaking on all of its tests.  It doesnt provide the args/params which sql-explorer expects, but that is the point - the forms should describe what they need, and fail form validation sanely if not provided.

The smoke tester has an option to exclude apps, so I have excluded sql-explorer, and as this is a dev-env only tool for us, that is ok, and this isnt a high priority.  Thanks for the great tool ;-)

```py
ERROR: test_smoke_PUT_admin/explorer-ui/new/$ (django_smoke_tests.tests.SmokeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django_smoke_tests/generator.py", line 90, in test
    response = http_method_function(url, {})
  File "/usr/lib/python3.8/site-packages/django/test/client.py", line 549, in put
    response = super().put(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/lib/python3.8/site-packages/django/test/client.py", line 380, in put
    return self.generic('PUT', path, data, content_type,
  File "/usr/lib/python3.8/site-packages/django/test/client.py", line 421, in generic
    return self.request(**r)
  File "/usr/lib/python3.8/site-packages/django/test/client.py", line 496, in request
    raise exc_value
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/explorer/views.py", line 89, in dispatch
    return super(PermissionRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/edit.py", line 149, in put
    return self.post(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/lib/python3.8/site-packages/django/forms/forms.py", line 180, in is_valid
    return self.is_bound and not self.errors
  File "/usr/lib/python3.8/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/usr/lib/python3.8/site-packages/django/forms/forms.py", line 376, in full_clean
    self._clean_fields()
  File "/usr/lib/python3.8/site-packages/django/forms/forms.py", line 394, in _clean_fields
    value = field.clean(value)
  File "/usr/lib/python3.8/site-packages/django/forms/fields.py", line 149, in clean
    self.validate(value)
  File "/usr/lib/python3.8/site-packages/explorer/forms.py", line 20, in validate
    passes_blacklist, failing_words = query.passes_blacklist()
  File "/usr/lib/python3.8/site-packages/explorer/models.py", line 62, in passes_blacklist
    return passes_blacklist(self.final_sql())
  File "/usr/lib/python3.8/site-packages/explorer/models.py", line 65, in final_sql
    return swap_params(self.sql, self.available_params())
  File "/usr/lib/python3.8/site-packages/explorer/models.py", line 90, in available_params
    p = extract_params(self.sql)
  File "/usr/lib/python3.8/site-packages/explorer/utils.py", line 39, in extract_params
    params = re.findall(regex, text.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by marksweb** [comment]
@jayvdb It'd be great if you could provide a PR for this.

**Comment by jayvdb** [comment]
Was this fixed?

**Comment by marksweb** [comment]
@jayvdb As it stands, you cannot execute a query with no SQL;

<img width="1217" alt="Screenshot 2020-12-07 at 23 40 36" src="https://user-images.githubusercontent.com/1461191/101418411-c04efb80-38e5-11eb-90a7-25e18650191c.png">

If the smoke test finds endpoints to test, in theory it should hit the same validation and the backend won't execute the query to hit the error you flagged.

If I've misunderstood this, please provide some more info on how to replicate what you've seen.

**Comment by jayvdb** [comment]
I have removed my exclusion rule for this app, and the errors occur again.

My guess is there is a soft limit preventing empty SQL, or something else is happening, and it should be able to work that out by stepping back through the backtrace to see what is None.

https://github.com/greyside/django-admin-smoke-tests is the smoke tester, https://github.com/jayvdb/django-smoke-tests/branches/drf is what I am using.

As per the readme, you only need to do `./manage.py test django_admin_smoke_tests.tests`

Pasted again with all of the tests which are failing.

```py
======================================================================
ERROR: test_smoke_POST_admin/explorer-ui/download (django_smoke_tests.tests.SmokeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/django-smoke-tests/django_smoke_tests/generator.py", line 90, in test
    response = http_method_function(url, {})
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 357, in post
    secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/explorer/views/auth.py", line 44, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/explorer/views/download.py", line 27, in post
    ql = query.log(request.user)
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 122, in log
    sql=self.final_sql(),
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 78, in final_sql
    return swap_params(self.sql, self.available_params())
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 105, in available_params
    p = extract_params(self.sql)
  File "/usr/local/lib/python3.6/site-packages/explorer/utils.py", line 45, in extract_params
    params = re.findall(regex, text.lower())
AttributeError: 'NoneType' object has no attribute 'lower'

======================================================================
ERROR: test_smoke_POST_admin/explorer-ui/new/ (django_smoke_tests.tests.SmokeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/django-smoke-tests/django_smoke_tests/generator.py", line 90, in test
    response = http_method_function(url, {})
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 357, in post
    secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/explorer/views/auth.py", line 44, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 399, in _clean_fields
    value = field.clean(value)
  File "/usr/local/lib/python3.6/site-packages/django/forms/fields.py", line 149, in clean
    self.validate(value)
  File "/usr/local/lib/python3.6/site-packages/explorer/forms.py", line 23, in validate
    passes_blacklist, failing_words = query.passes_blacklist()
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 75, in passes_blacklist
    return passes_blacklist(self.final_sql())
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 78, in final_sql
    return swap_params(self.sql, self.available_params())
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 105, in available_params
    p = extract_params(self.sql)
  File "/usr/local/lib/python3.6/site-packages/explorer/utils.py", line 45, in extract_params
    params = re.findall(regex, text.lower())
AttributeError: 'NoneType' object has no attribute 'lower'

======================================================================
ERROR: test_smoke_POST_admin/explorer-ui/play/ (django_smoke_tests.tests.SmokeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/django-smoke-tests/django_smoke_tests/generator.py", line 90, in test
    response = http_method_function(url, {})
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 357, in post
    secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/explorer/views/auth.py", line 44, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/explorer/views/query.py", line 43, in post
    passes_blacklist, failing_words = query.passes_blacklist()
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 75, in passes_blacklist
    return passes_blacklist(self.final_sql())
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 78, in final_sql
    return swap_params(self.sql, self.available_params())
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 105, in available_params
    p = extract_params(self.sql)
  File "/usr/local/lib/python3.6/site-packages/explorer/utils.py", line 45, in extract_params
    params = re.findall(regex, text.lower())
AttributeError: 'NoneType' object has no attribute 'lower'

======================================================================
ERROR: test_smoke_PUT_admin/explorer-ui/new/ (django_smoke_tests.tests.SmokeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/django-smoke-tests/django_smoke_tests/generator.py", line 90, in test
    response = http_method_function(url, {})
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 566, in put
    response = super().put(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 382, in put
    secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/explorer/views/auth.py", line 44, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 149, in put
    return self.post(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 399, in _clean_fields
    value = field.clean(value)
  File "/usr/local/lib/python3.6/site-packages/django/forms/fields.py", line 149, in clean
    self.validate(value)
  File "/usr/local/lib/python3.6/site-packages/explorer/forms.py", line 23, in validate
    passes_blacklist, failing_words = query.passes_blacklist()
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 75, in passes_blacklist
    return passes_blacklist(self.final_sql())
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 78, in final_sql
    return swap_params(self.sql, self.available_params())
  File "/usr/local/lib/python3.6/site-packages/explorer/models.py", line 105, in available_params
    p = extract_params(self.sql)
  File "/usr/local/lib/python3.6/site-packages/explorer/utils.py", line 45, in extract_params
    params = re.findall(regex, text.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
```
