### ISSUE TITLE
All Queries Produce "[HY010][Microsoft][ODBC Driver for SQL Server] Function sequence error (0) (SQLFetch)"

### ISSUE THREAD

**Issue by MYX-GitHub** [groveco/django-sql-explorer#423]
I just upgraded SQL Explorer from v1.1.3 to v2.0b and now all queries produce the same runtime error when opened:

'HY010', '[HY010] [Microsoft][ODBC Driver 13 for SQL Server]Function sequence error (0) (SQLFetch)'

All queries are on the same table in SQL Server 2014 and worked without issue in v1.1.3. The SQL Explorer home page updates properly, adding/updating items to the Most Recently Run list with the right date, even though the query did not actually run. Can navigate to the Playground page and view the schema, but even the simplest query produces the same error.

Django and other components are current, and also tried updating  to ODBC Driver 17, and getting the same results. The stack trace is shown below.

Researching the issue shows that common causes include issuing a Commit after a Select, and order of operations regarding cursors, including async operations too quickly. (Adding the AutoCommit = False option in Settings does not change anything

Note that v2.0b does fix "virtual foldering" issues in the home page query list, which was the main reason to upgrade.

Please advise.

Thanks,

Mike

Error at /explorer/15/
('HY010', '[HY010] [Microsoft][ODBC Driver 13 for SQL Server]Function sequence error (0) (SQLFetch)')
	Request Method:		GET
	Request URL:			http://fja-dev-im:8000/explorer/15/
	Django Version:		3.1.4
	Exception Type:		Error
	Exception Value:		('HY010', '[HY010] [Microsoft][ODBC Driver 13 for SQL Server]Function sequence error (0) (SQLFetch)')
	Exception Location:	\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\sql_server\pyodbc\base.py, line 601, in fetchall
	Python Executable:		\\FSE0238\myxhome$\Projects\GEAR\Django\env\Scripts\python.exe
	Python Version:		3.8.2
	Python Path:	
				['F:\\Projects\\GEAR\\Django\\GEAR_DSE',
				 '\\\\FSE0238\\myxhome$\\Projects\\GEAR\\Django\\env\\Scripts\\python38.zip',
				 'C:\\Program Files (x86)\\Python38-32\\Lib',
				 'C:\\Program Files (x86)\\Python38-32\\DLLs',
				 'c:\\users\\myxaccnt\\appdata\\local\\programs\\python\\python38-32',
				 '\\\\FSE0238\\myxhome$\\Projects\\GEAR\\Django\\env',
				 '\\\\FSE0238\\myxhome$\\Projects\\GEAR\\Django\\env\\lib\\site-packages']
	Server time:		Tue, 08 Dec 2020 14:41:47 +0000

Environment:

Request Method: GET
Request URL: http://fja-dev-im:8000/explorer/15/

Django Version: 3.1.4
Python Version: 3.8.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'explorer']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\django\db\utils.py", line 97, in inner
    return func(*args, **kwargs)
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\sql_server\pyodbc\base.py", line 601, in fetchall
    return self.format_rows(self.cursor.fetchall())

The above exception (('HY010', '[HY010] [Microsoft][ODBC Driver 13 for SQL Server]Function sequence error (0) (SQLFetch)')) was the direct cause of the following exception:
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\explorer\views\auth.py", line 44, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\explorer\views\query.py", line 97, in get
    vm = query_viewmodel(
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\explorer\views\utils.py", line 19, in query_viewmodel
    res, ql = query.execute_with_logging(user)
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\explorer\models.py", line 87, in execute_with_logging
    ret = self.execute()
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\explorer\models.py", line 93, in execute
    ret = self.execute_query_only()
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\explorer\models.py", line 81, in execute_query_only
    return QueryResult(
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\explorer\models.py", line 194, in __init__
    self._data = [list(r) for r in cursor.fetchall()]
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\django\db\utils.py", line 97, in inner
    return func(*args, **kwargs)
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\django\db\utils.py", line 97, in inner
    return func(*args, **kwargs)
  File "\\FSE0238\myxhome$\Projects\GEAR\Django\env\lib\site-packages\sql_server\pyodbc\base.py", line 601, in fetchall
    return self.format_rows(self.cursor.fetchall())

Exception Type: Error at /explorer/15/
Exception Value: ('HY010', '[HY010] [Microsoft][ODBC Driver 13 for SQL Server]Function sequence error (0) (SQLFetch)')

**Comment by marksweb** [comment]
This sounds like it requires access to MS SQL to investigate, so we'll need some help to do this.

**Comment by NodeJSmith** [comment]
I found that this happened with both mssql-django and django-mssql-backend. However, I was able to fix it on both by adding the following line to the database dictionary:

```        
'AUTOCOMMIT': False,
```

Example:
```
    return {
        'ENGINE': 'mssql',
        'AUTOCOMMIT': False,
        'NAME': 'Test',
        'HOST': database,
        'PORT': '1433',
        'TIME_ZONE': 'America/Chicago',
        'OPTIONS': {'driver': 'ODBC Driver 17 for SQL Server'}
    }
```

**Comment by marksweb** [comment]
@NodeJSmith Thank you for sharing this! Hopefully this works for others!!

@MYX-GitHub check out this possible solution.

I'll close this, but if needs be feel free to reopen.
